#!/bin/bash
# Author: Joshua Chen
# Date: 2014-04-30
# Location: Shenzhen
# Name: b2e
# Description: read the data from the STDIN, compress it,
# encrypt it, and send it to the email server as an attachment

recipient="{{RECIPIENT}}"
keyid="{{GPGKEYID}}"
MAILER="mutt -F {{BASEDIR}}/conf/muttrc"

if [ "$#" -eq 2 ]; then
    subject="$2"
    content="$(date +'%Y-%m-%d %H:%M:%S'), $subject"
    attachment=$(mktemp $(date +%s).XXXXXXXXXX)
    cat | xz -9 | gpg -z 0 -er "$keyid" > $attachment
    echo "$content" | $MAILER $recipient -s "$subject" -a "$attachment"
    result=$?

    # clean and exit
    rm -f $attachment
    exit $result
else
    echo "Usage: DATA FLOW | $(basename $0) -s [SUBJECT]"
    exit 1
fi

